---
- name: Patch RHEL 7 and RHEL 8 servers without reboot and show latest kernel
  hosts: all
  become: true
  gather_facts: true

  vars:
    kernel_pkg_rhel7: "kernel"
    kernel_pkg_rhel8: "kernel-core"

  tasks:

    - name: Determine OS major version
      ansible.builtin.set_fact:
        os_major_version: "{{ ansible_distribution_major_version | int }}"

    - name: Update all packages using 'package' module
      ansible.builtin.package:
        name: "*"
        state: latest

    - name: Get latest installed kernel on RHEL 7
      ansible.builtin.shell: "rpm -q {{ kernel_pkg_rhel7 }} | sort -V | tail -n 1"
      register: kernel_info_rhel7
      changed_when: false
      when: os_major_version == 7

    - name: Get latest installed kernel on RHEL 8
      ansible.builtin.shell: "rpm -q {{ kernel_pkg_rhel8 }} | sort -V | tail -n 1"
      register: kernel_info_rhel8
      changed_when: false
      when: os_major_version == 8

    - name: Show latest kernel on RHEL 7
      ansible.builtin.debug:
        msg: "Latest installed kernel on RHEL 7: {{ kernel_info_rhel7.stdout }}"
      when: os_major_version == 7

    - name: Show latest kernel on RHEL 8
      ansible.builtin.debug:
        msg: "Latest installed kernel on RHEL 8: {{ kernel_info_rhel8.stdout }}"
      when: os_major_version == 8
